name: test
env:
  GO_VERSION: 1.16
on:
  push:
    branches:
      - master
jobs:

  test:
    name:  Test
    runs-on: ubuntu-latest

    steps:
      - name: pull image
        run: |
          docker pull rodolpheche/wiremock:latest
          docker run --rm rodolpheche/wiremock:latest --verbose

