name: test
env:
  GO_VERSION: 1.16
on:
  push:
    branches:
      - master
jobs:

  test:
    name:  Test
    runs-on: ubuntu-latest

    steps:
      - name: pull image
        uses: docker/build-push-action@v2
        with:
         pull: true
         tags: rodolpheche/wiremock:latest

